### ISSUE TITLE
Implementar contador de pandas mortos por escreverem "iOS" errado

### ISSUE THREAD

**Issue by barbosa** [iOSDevBR/iosdevbr-hubot#15]

**Comment by DougFischer** [comment]
O desafio segue aberto! :)

**Comment by fpg1503** [comment]
Vocês acham que faz mais sentido:

**Comment by fpg1503** [comment]
- manter um contador geral (animais/palavras)

**Comment by fpg1503** [comment]
- manter um contador por palavra (ignorando animais)

**Comment by fpg1503** [comment]
- manter um contador por animal (ignorando palavras)
