### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by leonardocardoso** [iOSDevBR/iosdevbr-hubot#18]
Palavra `homosexual` escrita errada em [code-of-conduct.coffee#L20](https://github.com/iOSDevBR/iosdevbr-hubot/blob/cbd924ebaffe31e616e1339c00e1ac5abb293047/scripts/code-of-conduct.coffee#L20)

**Comment by barbosa** [comment]
Corrigido. Obrigado, @LeonardoCardoso 👍
